<a href="https://colab.research.google.com/github/igrosny/libros/blob/master/IMLP/Capitulo_1_Introduccion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Machine Learning with Python
## Capitulo 1: Introduccion

### Numpy

Contiene funciones para arreglo multidimensionales y algebra lineal

In [4]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

### SciPy

Algebra lineal avanzada, distribuciones estadisticas


In [8]:
from scipy import sparse

# Creaer un arreglo 2d con la diagonal en 1 y el resto 0 (la matriz identidad)
identidad = np.eye(4)

print("Arreglo Numpy:\n%s" % identidad)

# Convertir el arreglo numpy en una matriz sparse scipy en formato CSR
# donde solo los valores != 0 son guardados

sparse_matriz = sparse.csr_matrix(identidad)
print("\nScipy sparse CSR matriz:\n%s" % sparse_matriz)

Arreglo Numpy:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Scipy sparse CSR matriz:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
